[keymap]
destructive_delete = true
preset = "vim"

[keymap.overrides]
"cell.hideCode" = "Cmd-Shift-a"

[snippets]
include_default_snippets = true
custom_paths = []

[formatting]
line_length = 79

[server]
browser = "default"
follow_symlink = false

[experimental]
inline_ai_tooltip = true

[completion]
copilot = false
activate_on_typing = true

[diagnostics]
sql_linter = true

[package_management]
manager = "uv"

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[mcp]
presets = []

[mcp.mcpServers]

[runtime]
reactive_tests = true
std_stream_max_bytes = 1000000
dotenv = []
auto_instantiate = false
default_auto_download = []
on_cell_change = "lazy"
output_max_bytes = 8000000
auto_reload = "autorun"
default_sql_output = "auto"
pythonpath = []
watcher_on_save = "lazy"

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.models]
displayed_models = []
custom_models = []

[ai.google]

[language_servers.pylsp]
enable_mypy = true
enable_flake8 = false
enabled = true
enable_pydocstyle = false
enable_ruff = true
enable_pyflakes = false
enable_pylint = false

[display]
default_width = "medium"
code_editor_font_size = 16
reference_highlighting = false
dataframes = "rich"
default_table_page_size = 10
cell_output = "above"
theme = "system"
default_table_max_columns = 50
